on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.3

