on: push

jobs:
  main:
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Jekyll for GitHub Pages
        uses: actions/jekyll-build-pages@v1.0.6


      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.3
