name: Auto deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install

    - name: Build
      run: |
        npm run predeploy
        
    - name: Deploy
      run: |
        git config user.email "vadym.baranov@hotmail.com"
        git config user.name "vadymbaranov"
        npm run deploy

